[package]
name = "scholarsync-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
async-openai = { version = "0.28.1", features = ["byot"] }
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
